services:
  develop:
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    tty: true
    environment:
      TZ: Asia/Tokyo